name: tappy_wizard
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.0
  audioplayers: ^5.2.0

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/sounds/
    - assets/fonts/

  fonts:
    - family: MagicSchoolOne
      fonts:
        - asset: assets/fonts/MagicSchoolOne.ttf
